//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automobil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Automobil()
        {
            this.Pregledi = new HashSet<Pregled>();
        }
    
        public int SASIJA { get; set; }
        public string Marka { get; set; }
        public string TipMot { get; set; }
        public int ServisIDS { get; set; }
        public int BrSK { get; set; }
        public System.DateTime DatSK { get; set; }
    
        public virtual Servis Servis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregled> Pregledi { get; set; }
    }
}
