//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Popravljen
    {
        public long PokvarenPregledAutomobilSASIJA { get; set; }
        public long PokvarenPregledDijagnosticarJMBG { get; set; }
        public int PokvarenDeoDEOID { get; set; }
        public int MajstorZaDeoDEOID { get; set; }
        public long MajstorZaMajstorJMBG { get; set; }
        public System.DateTime DatPop { get; set; }
    
        public virtual Pokvaren Pokvaren { get; set; }
        public virtual MajstorZa MajstorZa { get; set; }
    }
}
