//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregled
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pregled()
        {
            this.Pokvareni = new HashSet<Pokvaren>();
        }
    
        public System.DateTime DatPre { get; set; }
        public bool Stanje { get; set; }
        public int AutomobilSASIJA { get; set; }
        public int DijagnosticarJMBG { get; set; }
    
        public virtual Automobil Automobil { get; set; }
        public virtual Dijagnosticar Dijagnosticar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pokvaren> Pokvareni { get; set; }
    }
}
