//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serviser
    {
        public int JMBG { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string TipServ { get; set; }
        public Nullable<int> ServisIDS { get; set; }
    
        public virtual Servis Servis { get; set; }
    }
}
